added tunnel plugin to krew
kubernetes-sigs/krew-index pull request #1280
Opened 2021-05-12 09:55 UTC by omrikiei

Added a plugin manifest for a tunnel([ktunnel](https://github.com/omrikiei/ktunnel))

2021-05-12 09:59 UTC, omrikiei commented
/check-cla

2021-05-12 17:39 UTC, ahmetb commented on plugins/tunnel.yaml
> +  shortDescription: Establishes a reverse tunnel between a kubernetes cluster and your local machine
Please shorten to fit ~65 chars.

2021-05-12 17:40 UTC, ahmetb commented on plugins/tunnel.yaml
> +    It lets you expose your machine as a service in the cluster or expose it to a specific deployment as a local host.
please line wrap at 80 chars.
Kubernetes capitalized.

2021-05-12 17:41 UTC, ahmetb commented
The name `tunnel` is a common word, but not so common in Kubernetes context. I think it is fine to assign to first-comer in this case. @corneliusweig @chriskim06 thoughts?

2021-05-12 17:57 UTC, chriskim06 commented
I second that, the name seems fine to me. Cool plugin btw 😄

2021-05-12 20:42 UTC, ahmetb commented on plugins/tunnel.yaml
> +specific deployment as a local host.
I think you need to indent this in. see other manifests as an example.

2021-05-12 20:43 UTC, ahmetb requested changes

2021-05-12 20:43 UTC, ahmetb commented on plugins/tunnel.yaml
> +  shortDescription: Establish a reverse tunnel between Kubernetes your local machine
I will make this shorter for you:

> Reverse tunneling between cluster and your machine

2021-05-13 10:18 UTC, corneliusweig commented
I haven't looked carefully yet, so just my 2cent for now:

- We already have a few plugins for tunneling/forwarding/proxying requests. I think it would make sense to pick a more descriptive name, such as `reverse-tunnel` (so something with reverse, because this seems to be the main use case)
- telemetry.io is a pretty popular project for the same purpose. How does your plugin compare to that solution?

2021-05-13 16:29 UTC, omrikiei commented
> I haven't looked carefully yet, so just my 2cent for now:
> 
> * We already have a few plugins for tunneling/forwarding/proxying requests. I think it would make sense to pick a more descriptive name, such as `reverse-tunnel` (so something with reverse, because this seems to be the main use case)
> * telemetry.io is a pretty popular project for the same purpose. How does your plugin compare to that solution?

Hey @corneliusweig, which other tunneling plugins are listed? I'd like to take a look. could you also share some reference to telemetry.io? I wasn't able to find anything in that context.. did you mean telepresence.io?

2021-05-14 22:16 UTC, corneliusweig commented
Meh.. I should not type on phone  :). Sorry for the confusion.

You're right, I meant telepresence.io. The other tunnel plugins are
- net-forward
- socks5-proxy
- tap

2021-05-15 00:20 UTC, omrikiei commented
telepresense substitutes a two-way network proxy for your normal pod running in the Kubernetes cluster.. it would start a dedicated shell and proxy all the resource coupled with the deployment to that shell.
ktunnel is a reverse network proxy and has only this functionality - it can be used for various use cases like [remote debugging](https://github.com/omrikiei/ktunnel/tree/master/examples/pycharm-remote-debugging-on-k8s#readme) (which is why I originally built it), metrics population, file transfer and I've seen [other cool usages as well](http://mbuffett.com/posts/ktunnel-ngrok-replace/).
ktunnel is not only limited for use in kubernetes, and it doesn't replace any remote resources with local ones

2021-05-15 14:31 UTC, corneliusweig reviewed
Ok, thanks for the explanation. Let's add this then. I have a minor wording (and text wrapping) suggestion, otherwise this is good to go!

Thanks for contributing!
/approve

---

Btw, you can shorten https://github.com/omrikiei/ktunnel/blob/6a5d8af7c979f877d63153932c0e032c410bea59/pkg/k8s/common.go#L25-L28 to
```go
_ "k8s.io/client-go/plugin/pkg/client/auth"
```
Then you will also get additional auth provider when they are added.

2021-05-15 14:31 UTC, corneliusweig commented on plugins/tunnel.yaml
> +specific deployment as a local host.
```suggestion
      This plugin establishes a reverse tunnel between the Kubernetes cluster
      and your local machine. It lets you expose your machine as a service in
      the cluster or expose it to a specific deployment as a local host.
```

2021-05-15 17:38 UTC, omrikiei commented
> https://github.com/omrikiei/ktunnel/blob/6a5d8af7c979f877d63153932c0e032c410bea59/pkg/k8s/common.go#L25-L28

I like the way you think

2021-05-15 17:44 UTC, corneliusweig commented
/lgtm
/approve
Thanks for contributing!

2021-05-15 17:45 UTC, merged

2021-05-16 16:43 UTC, ahmetb commented
Also, please consider setting up [Krew release automation](https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/) which helps you skip manually making updates to your Krew manifests on each new version and send a pull request. It’s a GitHub workflow bot that can run every time you push a new tag. Those PRs are automatically approved.