`kubectl secretdata` plugin
kubernetes-sigs/krew-index pull request #1903
Opened 2022-01-10 22:42 UTC by kei6u

This patch introduces `kubectl secretdata` as a kubectl plugin.

**Local installation**

![Screen Shot 2022-01-11 at 7 41 08](https://user-images.githubusercontent.com/41987730/148850361-07348587-5c01-4126-ac21-eebd2bc97002.png)

**Plugin help**

![Screen Shot 2022-01-11 at 7 41 50](https://user-images.githubusercontent.com/41987730/148850419-c998deb6-2a1d-45f6-be46-f9a3dd0c640f.png)

2022-01-10 22:42 UTC, ahmetb commented
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

2022-01-10 23:13 UTC, ahmetb commented
This seems to be an enhanced version of https://github.com/elsesiy/kubectl-view-secret plugin. I think I approve the idea.
/approve

2022-01-10 23:14 UTC, ahmetb requested changes

2022-01-10 23:14 UTC, ahmetb commented on plugins/secretdata.yaml
> +  shortDescription: A kubectl plugin for finding decoded secret data with productive search flags
> A kubectl plugin for

unnecessary

> secret

please capitalize as Secret (consistent with Kubernetes docs).

> finding

is this plugin for "finding" or "viewing"? 

please make sure this field fits 50 chars.

2022-01-10 23:14 UTC, ahmetb commented on plugins/secretdata.yaml
> +    you want with productive search flags.
you can use up to 80 chars wide (excluding the preceding spaces), this seems quite narrow.

2022-01-10 23:28 UTC, kei6u commented
@ahmetb Thank you for your review! Updated descriptions. 1d51438

2022-01-13 23:15 UTC, ahmetb commented
/lgtm
/approve

2022-01-13 23:16 UTC, merged