add the Datree plugin to the repository
kubernetes-sigs/krew-index pull request #1952
Opened 2022-01-31 10:47 UTC by hadar-co

Tested locally: :)
```
Installing plugin: datree
Installed plugin: datree
\
 | Use this plugin:
 | 	kubectl datree
 | Documentation:
 | 	https://github.com/datreeio/kubectl-datree
/
```

2022-01-31 10:47 UTC, ahmetb commented
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

2022-01-31 11:34 UTC, hadar-co commented
CLA has been signed, please review again:)
@k8s-ci-robot

2022-02-02 07:54 UTC, hadar-co commented
/check-cla

2022-02-02 08:03 UTC, hadar-co commented
@ahmetb @chriskim06 
Hi :)
Please assist in advancing this PR to completion. I have signed the CLA, how do I prompt a retest?
Thanks!

2022-02-02 08:16 UTC, ahmetb commented
I've left a comment, is it not visible to you?

2022-02-02 08:42 UTC, hadar-co commented
@ahmetb
My bad, I missed it.. thanks :)

2022-02-02 14:52 UTC, hadar-co commented
@ahmetb 
I realized that my user was not linked to my commit, I fixed that.
Now the manifest validation produces this error:

I0202 14:46:21.358190    1983 downloader.go:54] Extracting zip archive to "/tmp/krew-downloads934326152"
I0202 14:46:21.358522    1983 install.go:101] Deleting the download staging directory /tmp/krew-downloads934326152
	W0202 14:46:21.358700    1983 install.go:164] failed to install plugin "datree": install failed: failed to unpack into staging dir: failed to unpack the plugin archive: failed to extract file: can't create file in zip destination dir: open /tmp/krew-downloads934326152/__MACOSX/._LICENSE: no such file or directory

Any idea why this happens? Locally the installation works.
Thanks for the help :)

2022-02-02 16:58 UTC, ahmetb commented
> Scan your k8s files in cluster

But there are no files within the cluster?

Does this call the Kubernetes apiserver at all or is it a static file validator? If so it shouldn't be a kubectl plugin probably.

2022-02-02 18:16 UTC, ahmetb requested changes
sorry I realized github mobile app didn't publish this

2022-02-02 19:08 UTC, ahmetb commented
I think both your website and your plugin description is doing a suboptimal job explaining what the plugin does.

There are no "files" or "manifests" in a cluster. They live on your filesystem. Once it reaches the cluster, it's a resource/API object. That's why right now your documentation and plugin description sound quite odd to me. I thought it scans my local files and matches them with the corresponding live resources on the cluster, but apparently that's not it.

I'll let you iterate on those, otherwise we'd be doing disservice to users. Also words like k8s are redundant in the short description.

2022-02-03 09:37 UTC, hadar-co commented
@ahmetb 
Thanks for the comments, I definitely agree that the wording was unclear.
I fixed it and recommitted.

The plugin validation is still failing with the error I pasted in my last comment, can you please assist?
Thank you

2022-02-03 16:27 UTC, ahmetb requested changes

2022-02-03 16:27 UTC, ahmetb commented on plugins/datree.yaml
> +  caveats: |
If empty, omit.

2022-02-03 16:27 UTC, ahmetb commented on plugins/datree.yaml
> +  shortDescription: Scan the resources within your cluster for misconfigurations
This is too long. Should be 50 max.

2022-02-04 06:15 UTC, ahmetb commented on plugins/datree.yaml
> +    Datree is a static code analysis tool for k8s manifest files. This plugin extends the tool's capabilities
k8s → Kubernetes

It's unclear what "the tool" here is.

2022-02-04 17:26 UTC, hadar-co commented
@ahmetb 
Fixed :)

2022-02-05 01:29 UTC, ahmetb commented
Two points

1. right now the tests are failing because of a bug we fixed, try this:

       git fetch origin
       git rebase origin/master
       git push -f

2. your plugin installs random stuff to users' computer, which is not what any user wants, or any program you download from a package manager would do, and we can't accept the plugin like that:

    ```sh
      # Install datree if it isn't installed
      if ! command -v datree &> /dev/null; then
          echo "Datree is not installed on your machine, proceeding to install..."
          curl https://get.datree.io | /bin/bash
      fi
    ```

    I can recommend (1) not distributing the external tool, many other plugins do this and asks users to install additional programs in caveats section (2) bundle the external tool in your plugin archive and extract it and call to it. it doesn't have to be in $PATH to be called by your plugin, you can find its path by looking at the currently executing executable's path and resolving its symlink (3) make your main executable the plugin binary, and make it run as a kubectl plugin by looking at os.Argv[0] and observing the kubectl- prefix.

As it stands today, plugins installing other programs to the system are not acceptable.
/hold

2022-02-06 10:48 UTC, hadar-co commented
@ahmetb 
Got it, I went with suggestion (1) :)

2022-02-08 09:53 UTC, hadar-co commented
@ahmetb 
Hi, is something still blocking the approval?
Thanks

2022-02-08 20:03 UTC, ahmetb commented
/lgtm
/approve
Thanks!

2022-02-08 20:22 UTC, ahmetb commented
/hold cancel

2022-02-08 20:22 UTC, merged