Add aws-auth v0.3.5
kubernetes-sigs/krew-index pull request #2159
Opened 2022-04-11 17:29 UTC by eytan-avisror

2022-04-11 17:29 UTC, ahmetb commented
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

2022-04-11 17:32 UTC, eytan-avisror commented
/assign @ahmetb

2022-04-11 17:41 UTC, ahmetb commented
Have you read the naming guidelines? That name won't work.

2022-04-11 17:45 UTC, eytan-avisror commented
@ahmetb I have, can you be a bit more specific on why it won't work? is it too generic?

2022-04-11 17:46 UTC, ahmetb commented
Has vendor prefix and is too generic. AWS or someone else can submit a plugin with the same name that works entirely differently.

2022-04-11 17:50 UTC, eytan-avisror commented
@ahmetb can you suggest a better name for the plugin? the purpose is easy modification/management of the 'aws-auth' configmap present on EKS clusters.
is `aws-auth-manager` any better?

2022-04-11 18:11 UTC, eytan-avisror commented
BTW @ahmetb 
Not sure if it makes a difference but this tool is referenced by AWS best practices here: https://github.com/aws/aws-eks-best-practices/blob/master/content/security/docs/iam.md#use-tools-to-make-changes-to-the-aws-auth-configmap

And also the suggestion to add a krew plugin was by AWS here:
https://github.com/keikoproj/aws-auth/issues/30

2022-04-11 18:58 UTC, eytan-avisror commented
@ahmetb `aws-eks-auth-mapper` kinda long, but perhaps more specific. would that be more acceptable?

2022-04-11 19:08 UTC, ahmetb commented
edit-aws-auth can work too.
aws-auth can work if you can get thumbs up from AWS folks that they don't plan on using the name. I thought you might have a chance there since they're aware of this tool.

2022-04-11 19:09 UTC, ahmetb commented
Also the fact that there's a notable existing user community and recognition from the vendor, we can consider this as an established solution and assign the name I think.

2022-04-11 19:12 UTC, eytan-avisror commented
Thanks @ahmetb 
I've pinged the original requestor for the plugin (from AWS) to comment here

2022-04-11 21:13 UTC, eytan-avisror commented
Thanks @jicowan 
@ahmetb I can make the changes, is it OK though that the plugin name differs from the repo name & binary name?

2022-04-11 21:20 UTC, ahmetb commented
Yeah, just make sure the -h/-help message doesn't confuse users with different names.

2022-04-11 21:22 UTC, jicowan commented
I would prefer to keep it the same (aws-auth) but if we think it'll be too confusing I'm in favor of changing it.

2022-04-11 21:24 UTC, eytan-avisror commented
@jicowan yeah I think it would actually be much nicer as a shorter name i.e. `kubectl aws-auth ...` - given that this is a pretty basic term on EKS clusters I don't see a reason where there might be a conflict with some other tooling.

2022-04-11 21:27 UTC, eytan-avisror commented
I think according to @ahmetb it's not about it being 'confusing', but more about if you foresee any conflict with the name in the future e.g. AWS wanting to introduce a different tool with that name as a krew plugin being is the word `auth` is somewhat generic

2022-04-11 21:34 UTC, jicowan commented
Ah, we have no intention of releasing a new CLI to modify the aws-auth ConfigMap. Rather, we are looking at ways we can assign Cluster access directly through IAM.

2022-04-11 21:36 UTC, ahmetb commented
Fair, then we can assign the name aws-auth especially given the tool is already known, used by a nontrivial amount of users and endorsed.

2022-04-11 21:57 UTC, eytan-avisror commented
Thanks @ahmetb & @jicowan 
Please let me know if there is anything else needed in order to get this merged.

2022-04-12 04:07 UTC, ahmetb requested changes

2022-04-12 04:20 UTC, eytan-avisror commented on plugins/aws-auth.yaml
> +
done

2022-04-12 04:20 UTC, eytan-avisror commented on plugins/aws-auth.yaml
> +  shortDescription: Makes the management of the aws-auth config map for EKS Kubernetes clusters easier
done

2022-04-12 04:20 UTC, eytan-avisror commented on plugins/aws-auth.yaml
> +    Useful for automation purposes, any workflow that needs
Done

2022-04-12 04:24 UTC, ahmetb commented
/lgtm
/approve
Thanks!


Also, please consider setting up [Krew release automation](https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/) which helps you skip manually making updates to your Krew manifests on each new version and send a pull request. It’s a GitHub workflow bot that can run every time you push a new tag. Those PRs are automatically approved.

2022-04-12 04:25 UTC, merged

2022-04-12 04:25 UTC, eytan-avisror commented
Thanks @ahmetb !