Add kubectl-point
kubernetes-sigs/krew-index pull request #2280
Opened 2022-05-22 09:51 UTC by davidchua

Creates a headless service to an external source with optional ingress

2022-05-22 09:51 UTC, ahmetb commented
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

2022-05-22 15:37 UTC, ahmetb requested changes

2022-05-22 15:37 UTC, ahmetb commented on plugins/point.yaml
> +  # 'name' must match the filename of the manifest. The name defines how
Please remove these comments.

2022-05-22 23:21 UTC, davidchua commented on plugins/point.yaml
> +  # 'name' must match the filename of the manifest. The name defines how
Yikes! Thanks! I've removed them

2022-05-23 01:04 UTC, ahmetb commented on plugins/point.yaml
> +  shortDescription: "Creates a headless service to an external source with optional ingress"
Just fyi this probably won't fit where it's shown and will be truncated. Limit to 50 chars if you can.

2022-05-23 01:04 UTC, ahmetb commented on plugins/point.yaml
> +    files:
This field is redundant if you do *,. like you do here.

2022-05-23 01:04 UTC, ahmetb commented on plugins/point.yaml
> +    Generates and creates a headless service and/or ingress to point to any external source
Add a trailing period and maybe go into just a little bit more into detail as to what the feature list is etc.

2022-05-23 06:31 UTC, davidchua commented
Thanks for the comments! Appreciate the time taken to review this!

Made the changes as requested. I had to take a bit more time to really think hard about how to make the description a bit more concise. I hope I got it!

2022-06-08 08:23 UTC, davidchua commented
/assign @ahmetb

2022-08-17 00:35 UTC, ahmetb commented
Sorry this entirely fell off my radar. Any problems with going ahead and accepting this?

2023-01-14 01:57 UTC, closed without merging