Add kubectl-kount plugin
kubernetes-sigs/krew-index pull request #2610
Opened 2022-09-17 11:59 UTC by adityajoshi12

2022-09-17 11:59 UTC, ahmetb commented
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

2022-09-17 12:06 UTC, adityajoshi12 commented
/assign @ahmetb

2022-09-20 16:13 UTC, adityajoshi12 commented
/assign @ahmetb

2022-09-20 16:39 UTC, ahmetb requested changes
sorry forgot to publish comments.

2022-09-20 16:52 UTC, adityajoshi12 commented on plugins/kount.yaml
> +  shortDescription: kount Kubernetes resource instances.
updated the shortDescription.

2022-09-20 16:53 UTC, adityajoshi12 commented on plugins/kount.yaml
> +    kubectl-kount is a subcommand of kubectl to to kount kubernetes object.
Added more details to description

2022-09-20 17:11 UTC, ahmetb commented
I've just had a chance to use the plugin and I'm afraid it doesn't meet the usefulness criteria. It doesn't do anything more interesting than `kubectl get -n NAMESAPCE RESOURCE_TYPE | wc -l`. We typically reject plugins that are easily achievable with such one-liner commands.

2022-09-20 17:12 UTC, ahmetb commented
/close

2022-09-20 17:20 UTC, adityajoshi12 commented
This is just the initial release, next release is going to have have more features like detailed view and group by namespaces.

2022-09-20 17:22 UTC, adityajoshi12 commented
/open

2022-09-20 17:23 UTC, adityajoshi12 commented
/reopen

2022-09-20 17:31 UTC, ahmetb commented
Understood, but you should consider submitting the plugin when that becomes the case. As it stands right now, the plugin doesn't meet the usefulness criteria. Also, I recommend you to think more broadly in terms of querying/grouping objects besides just counting. In that case, "kount" name no longer becomes useful either. So please take more time developing your plugin, which may help you better understand what you want to build and what to name it.

2022-12-20 03:34 UTC, closed without merging