Added kubectl-ansible-playbook
kubernetes-sigs/krew-index pull request #814
Opened 2020-09-14 14:47 UTC by Akasurde

Added support for new Kubectl plugin. With this
plugin user can execute Ansible Playbooks on Kubernetes Pods
with help of Ansible K8S dynamic inventory and kubectl connection
plugin.

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

2020-09-20 12:02 UTC, corneliusweig requested changes
This plugin has nothing to do with kubernetes per se. The plugin is merely a wrapper of `ansible-playbook` (https://github.com/Akasurde/kubectl-ansible-playbook/blob/804eb981e71888deb4b0d39df95a2dcb3348583c/kubectl-ansible_playbook#L82) and runs on the user's machine.

Given that these dependencies need to be installed manually, I see little benefit of having this as a kubectl plugin.

Am I wrong?

2020-09-21 07:02 UTC, Akasurde commented
> This plugin has nothing to do with kubernetes per se. The plugin is merely a wrapper of `ansible-playbook` ([Akasurde/kubectl-ansible-playbook@`804eb98`/kubectl-ansible_playbook#L82](https://github.com/Akasurde/kubectl-ansible-playbook/blob/804eb981e71888deb4b0d39df95a2dcb3348583c/kubectl-ansible_playbook#L82)) and runs on the user's machine.
> 

Yes. This is a wrapper around the Ansible playbook command but it uses Ansible kubectl connection plugin internally.

> Given that these dependencies need to be installed manually, I see little benefit of having this as a kubectl plugin.
> 
> Am I wrong?

I see a lot of potentials here. Let us assume user has Ansible configured and want to run configure already running pods with some operations like - 

```

# kubectl ansible-playbook -i k8s.yml --limit namespace_test_pods main.yml -vv
Using: k8s.yml as inventory
ansible-playbook 2.11.0.dev0
  config file = None
  configured module search path = ['/Users/akasurde/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Volumes/data/src/ansible/lib/ansible
  ansible collection location = /Volumes/data/src/collections
  executable location = /Volumes/data/src/ansible/bin/ansible-playbook
  python version = 3.7.4 (default, Sep  7 2019, 18:27:02) [Clang 10.0.1 (clang-1001.0.46.4)]
No config file found; using defaults
PLAYBOOK: main.yml ****************************************************************************
1 plays in main.yml

PLAY [all] ************************************************************************************

TASK [Gathering Facts] ************************************************************************
task path: /Volumes/data/src/playbooks/k8s/inventory/main.yml:2
redirecting (type: connection) ansible.builtin.kubectl to community.kubernetes.kubectl
ok: [nginx-server_nginx-server]
META: ran handlers

TASK [shell] **********************************************************************************
task path: /Volumes/data/src/playbooks/k8s/inventory/main.yml:4
redirecting (type: connection) ansible.builtin.kubectl to community.kubernetes.kubectl
changed: [nginx-server_nginx-server] => {"changed": true, "cmd": "hostname", "delta": "0:00:00.432226", "end": "2020-09-21 06:58:31.589306", "rc": 0, "start": "2020-09-21 06:58:31.157080", "stderr": "", "stderr_lines": [], "stdout": "nginx-server", "stdout_lines": ["nginx-server"]}
META: ran handlers
META: ran handlers

PLAY RECAP ************************************************************************************
nginx-server_nginx-server  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

# cat k8s.yml
plugin: community.kubernetes.k8s
connections:
  - namespaces:
    - test
# cat main.yml
---
- hosts: all
  tasks:
    - shell: hostname
```

Let me know if you need anything from my side. Thanks.

2020-09-22 22:32 UTC, ahmetb commented
I'm looking at your source code https://github.com/Akasurde/kubectl-ansible-playbook/blob/76033bb2c132af6ed5ab4fe312ac9bf3316d5e49/kubectl-ansible_playbook and this doesn't seem to interact with kubectl or Kubernetes API. 

So your plugin seems to be a script that basically just does `ansible-playbook -i ${k8s_inventory_file} --limit ${limit} ${playbook}`. 

We typically reject these sort of plugins since they don't add enough value and usefulness to a broad range of kubectl users. We don't accept plugins based on their "potential" but rather existing value they provide.

I’ll go ahead and close this. If you want, you can still distribute this plugin using custom indexes feature.
/close

2020-09-22 22:32 UTC, closed without merging

2020-09-23 03:02 UTC, Akasurde commented
> I'm looking at your source code [Akasurde/kubectl-ansible-playbook@`76033bb`/kubectl-ansible_playbook](https://github.com/Akasurde/kubectl-ansible-playbook/blob/76033bb2c132af6ed5ab4fe312ac9bf3316d5e49/kubectl-ansible_playbook) and this doesn't seem to interact with kubectl or Kubernetes API.

Internally, Ansible uses kubectl and Kubernetes APIs to retrieve information about k8s objects.
Anyways.