Add kubectl-hlf plugin
kubernetes-sigs/krew-index pull request #961
Opened 2020-12-19 18:43 UTC by Dviejopomata

2020-12-19 18:44 UTC, Dviejopomata commented
/assign @ahmetb

2020-12-19 18:55 UTC, Dviejopomata commented
I signed it

2020-12-20 22:22 UTC, ahmetb requested changes
Thanks for your submission.

2020-12-20 22:22 UTC, ahmetb commented on plugins/hlf.yaml
> +  shortDescription: "Deploy and manage Hyperledger Fabric Peers, Orderers and Certificate authorities"
Please try to shorten this to ~50 chars.

2020-12-20 22:22 UTC, ahmetb commented on plugins/hlf.yaml
> +    interface to create and manage Hyperledger Fabric Peers, Orderers and Certificate authorities
Please try to  wrap lines at 80 chars for readability in user's cli.

2020-12-21 17:52 UTC, ahmetb commented
You need to amend your commit to remove my handle.

Also, have you followed this advice about auth plugins: https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/#auth-plugins

2020-12-21 22:05 UTC, Dviejopomata commented
No, I'm fixing it.
https://github.com/kfsoftware/hlf-operator/pull/6

I have already fixed the commit message.

2020-12-21 23:23 UTC, ahmetb commented
/lgtm
/assign @corneliusweig 
For approval

2020-12-24 08:34 UTC, Dviejopomata commented
Is there anything I can do from my side to merge this PR? @ahmetb

2020-12-24 09:28 UTC, corneliusweig commented
Sorry it takes so long, but it's holiday season and that includes kids :).
Will take a look when possible. In the meantime thanks for your patience!

On Thu, Dec 24, 2020, 09:34 Dviejo <notifications@github.com> wrote:

> Is there anything I can do from my side to merge this PR? @ahmetb
> <https://github.com/ahmetb>
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes-sigs/krew-index/pull/961#issuecomment-750806177>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFONMY6C4QMK7R7D5WTLWNLSWL4KHANCNFSM4VCPLBPA>
> .
>

2020-12-25 14:28 UTC, corneliusweig reviewed
/approve
Thanks for contributing! This looks pretty interesting.

2020-12-25 14:28 UTC, merged

2020-12-25 18:50 UTC, ahmetb commented
Also, please consider setting up [Krew release automation](https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/) which helps you skip manually making updates to your Krew manifests on each new version and send a pull request. It’s a GitHub workflow bot that can run every time you push a new tag. Those PRs are automatically approved.