Added new plugin flyte [flyte.org]
kubernetes-sigs/krew-index pull request #981
Opened 2021-01-13 19:46 UTC by evalsocket

- [ ] Make sure you read the Plugin Naming Guide: https://krew.sigs.k8s.io/docs/developer-guide/develop/naming-guide/
- [ ] Verify you can install your plugin locally

Below is the test output:
```
Installing plugin: flyte
Installed plugin: flyte
\
 | Use this plugin:
 |      kubectl flyte
 | Documentation:
 |      https://github.com/lyft/flyte
/

```

2021-01-13 21:12 UTC, ahmetb requested changes

2021-01-13 21:12 UTC, ahmetb commented on plugins/flyte.yaml
> +  shortDescription: kubectl-flyte is an command line tool for flyte that can be used as an extension to kubectl.
"Kubectl-flyte is a command line tool" is redundant. Keep it short and descriptive. 

Right now this description does not really convey any meaning. It is already clear that this is a plugin and it's about Flyte. ￼￼

2021-01-13 21:12 UTC, ahmetb commented on plugins/flyte.yaml
> +      kubectl-flyte is an command line tool for flyte that can be used as an extension to kubectl.
This doesn't describe anything to me really. Can you explain a but what Flyte does?

Please read other plugin descriptions that have an unfamiliar project name like this. See how they explain

2021-01-20 18:11 UTC, ahmetb commented
@evalsocket ping. 
Also are you someone who works on flyte plugin?
If not, we would much rather have the plugin authors package and offer it here. It wouldn't be appropriate to distribute their plugin here if they won’t be maintaining and releasing updates, setting up release automation etc.

2021-01-20 18:18 UTC, evalsocket commented
Yes......We have automation in place for releasing the krew plugin. It is actively maintain and used by the flyte user

2021-01-20 21:11 UTC, kumare3 commented
@evalsocket thank you for creating this PR. @ahmetb Let me propose the descriptions here and @evalsocket can adapt them?

`Short`: Monitor, Launch and Manage flyte executions using kubectl
`Long`: Kubectl-flyte can be used to manage workflows in a kubernetes cluster executed by FlytePropeller. Users can monitor, visualize executing workflows, delete/terminate executions in bulk, dive into quota utilization for tenants. The tool allows users to launch yaml based Flyte workflows without needing FlyteAdmin etc. For more information about Flyte refer to https://flyte.org

2021-01-20 21:52 UTC, ahmetb commented
Overall sounds good. 

Probably can shorten/fix this:

> Monitor, Launch and Manage flyte executions using kubectl

as

> Monitor, launch and manage flyte executions

Similarly, prefixes such as 

> Kubectl-flyte can be used to

are redundant.

2021-01-24 22:35 UTC, corneliusweig commented on plugins/flyte.yaml
> +      Kubectl-flyte can be used to manage workflows in a kubernetes cluster executed by FlytePropeller. Users can monitor, visualize executing workflows, delete/terminate executions in bulk, dive int
Please wrap at ~80chars so that it prints nicely on wide and narrow terminals.

2021-01-31 15:25 UTC, corneliusweig reviewed
Looks good. Thanks for contributing! I wrapped the description more evenly. Can you please incorporate this change into your automation?

/lgtm
/approve

2021-01-31 15:27 UTC, merged